# choose a random server port
server.port: 0

nimdojo:
  config:
    player: COMPUTER
    gameId: 2
    wsTurnUrl: ws://127.0.0.1:8080/turns
    wsMsgUrl: ws://127.0.0.1:8080/messages
    gameServer: http://localhost:8080